"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {api} from "@/lib/api";
import {buildSemanticQuery,embed} from "@/lib/embedding";
import type {Analysis,Audit,Hit,Proposal,Requirements,Validation} from "@/lib/types";

const steps=["Intake & requirements","Comparable designs","Preliminary analysis","Evidence","Concept schematic","Review & audit"];
const labels:Record<string,string>={heat_load_kw:"Heat load",coolant_type:"Coolant",coolant_concentration_pct:"Concentration",coolant_inlet_temp_c:"Inlet temperature",max_outlet_temp_c:"Maximum outlet",ambient_temp_c:"Ambient",available_flow_lpm:"Available flow",max_pressure_drop_kpa:"Allowable pressure drop",supply_voltage_v:"Supply",frequency_hz:"Frequency",max_width_mm:"Maximum width",max_depth_mm:"Maximum depth",max_height_mm:"Maximum height",redundancy:"Redundancy",communication_protocol:"Communications",environmental_rating:"Environmental rating"};
const units:Record<string,string>={heat_load_kw:"kW",coolant_concentration_pct:"%",coolant_inlet_temp_c:"°C",max_outlet_temp_c:"°C",ambient_temp_c:"°C",available_flow_lpm:"L/min",max_pressure_drop_kpa:"kPa",supply_voltage_v:"V",frequency_hz:"Hz",max_width_mm:"mm",max_depth_mm:"mm",max_height_mm:"mm"};
const scenarioName:Record<string,string>={clearly_feasible:"Clear feasible case",conditionally_feasible:"Conditional case",missing_critical_information:"Missing critical input",outside_validated_range:"Outside validated range",contradictory_requirements:"Contradictory input"};

type Scoped<T>={applicationId:string;value:T};
type SelectionRequest={applicationId:string;generation:number;controller:AbortController};
const isDrawable=(result:Analysis)=>["preliminarily_feasible","conditionally_feasible"].includes(result.status)&&result.missing_requirements.length===0&&result.contradictions.length===0&&Boolean(result.proposed_architecture);
const evidenceDesignation=(hit:Hit)=>{if(hit.status==="superseded")return"SUPERSEDED — EVIDENCE ONLY";if(!hit.recommendation_eligible&&hit.disqualification_reasons.some(reason=>reason.toLowerCase().includes("fail")))return"FAILED — EVIDENCE ONLY";if(!hit.recommendation_eligible)return"DISQUALIFIED — EVIDENCE ONLY";return hit.document_type==="historical_project"?"ELIGIBLE PRECEDENT":"CURRENT EVIDENCE"};

export function EngineeringWorkspace(){
  const [apps,setApps]=useState<{scenario:string;requirements:Requirements}[]>([]);const [active,setActive]=useState(0);const [selected,setSelected]=useState<Requirements|null>(null);const [validationState,setValidationState]=useState<Scoped<Validation>|null>(null);const [analysisState,setAnalysisState]=useState<Scoped<Analysis>|null>(null);const [projectsState,setProjectsState]=useState<Scoped<Hit[]>|null>(null);const [hitsState,setHitsState]=useState<Scoped<Hit[]>|null>(null);const [proposalState,setProposalState]=useState<Scoped<Proposal>|null>(null);const [svgState,setSvgState]=useState<Scoped<string>|null>(null);const [auditsState,setAuditsState]=useState<Scoped<Audit[]>|null>(null);const [mode,setMode]=useState("checking");const [busy,setBusy]=useState(false);const [errorState,setErrorState]=useState<Scoped<string>|null>(null);const [question,setQuestion]=useState("Which current evidence governs glycol and redundancy limits?");const [embedState,setEmbedState]=useState("Local model idle");const [reviewNote,setReviewNote]=useState("");const [openedState,setOpenedState]=useState<Scoped<Hit>|null>(null);const requestRef=useRef<SelectionRequest|null>(null);const generationRef=useRef(0);
  const applicationId=selected?.application_id??null;const scoped=<T,>(state:Scoped<T>|null)=>state&&state.applicationId===applicationId?state.value:null;const validation=scoped(validationState);const analysis=scoped(analysisState);const projects=scoped(projectsState)??[];const hits=scoped(hitsState)??[];const proposal=scoped(proposalState);const svg=scoped(svgState)??"";const audits=scoped(auditsState)??[];const error=scoped(errorState)??"";const opened=scoped(openedState);
  function current(request:SelectionRequest){const activeRequest=requestRef.current;return !request.controller.signal.aborted&&activeRequest?.applicationId===request.applicationId&&activeRequest.generation===request.generation}
  function clearDerived(){setValidationState(null);setAnalysisState(null);setProjectsState(null);setHitsState(null);setProposalState(null);setSvgState(null);setAuditsState(null);setErrorState(null);setOpenedState(null);setReviewNote("");setEmbedState("Investigation not yet complete")}
  function beginRequest(req:Requirements){requestRef.current?.controller.abort();const request={applicationId:req.application_id,generation:++generationRef.current,controller:new AbortController()};requestRef.current=request;setSelected(req);clearDerived();setBusy(true);return request}
  function recordError(request:SelectionRequest,error:unknown,fallback:string){if(current(request)&&!(error instanceof DOMException&&error.name==="AbortError"))setErrorState({applicationId:request.applicationId,value:error instanceof Error?error.message:fallback})}
  async function investigate(req:Requirements){const request=beginRequest(req);try{setEmbedState("Embedding application requirements locally…");const vector=await embed(buildSemanticQuery(req));if(!current(request))return;setEmbedState("384-dimensional application vector ready");const valid=await api.validate(req,request.controller.signal);if(!current(request)||valid.requirements.application_id!==request.applicationId)return;setValidationState({applicationId:request.applicationId,value:valid});const [a,r]=await Promise.all([api.analyze(req,vector,request.controller.signal),api.rank(req,vector,request.controller.signal)]);if(!current(request)||a.application_id!==request.applicationId)return;setAnalysisState({applicationId:request.applicationId,value:a});setProjectsState({applicationId:request.applicationId,value:r.projects});setMode(r.retrieval_mode);const p=await api.propose(a,request.controller.signal);if(!current(request)||p.application_id!==request.applicationId)return;setProposalState({applicationId:request.applicationId,value:p});if(isDrawable(a)){const drawing=await api.schematic(req,a.proposed_architecture!,request.controller.signal);if(!current(request))return;setSvgState({applicationId:request.applicationId,value:drawing.svg})}else setSvgState({applicationId:request.applicationId,value:""});const history=await api.audit(req.application_id,request.controller.signal);if(!current(request)||history.some(event=>event.application_id!==request.applicationId))return;setAuditsState({applicationId:request.applicationId,value:history})}catch(e){recordError(request,e,"Investigation failed")}finally{if(current(request))setBusy(false)}}
  async function upload(file?:File){if(!file)return;const controller=new AbortController();setBusy(true);try{const requirements=await api.extract(file,controller.signal);await investigate(requirements)}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError")){const id=requestRef.current?.applicationId??selected?.application_id??"bootstrap";setErrorState({applicationId:id,value:e instanceof Error?e.message:"Upload failed"})}}finally{if(!requestRef.current)setBusy(false)}}
  async function ask(){const request=requestRef.current;if(!request||!selected||request.applicationId!==selected.application_id)return;setEmbedState("Loading bundled ONNX model…");setBusy(true);try{const vector=await embed(question);if(!current(request))return;setEmbedState(`384-dimensional local vector ready`);const architecture=analysis&&isDrawable(analysis)?analysis.proposed_architecture??"all":"all";const result=await api.search(question,vector,architecture,request.controller.signal);if(!current(request))return;setHitsState({applicationId:request.applicationId,value:result.hits});setMode(result.retrieval_mode);setActive(3)}catch(e){if(current(request))setEmbedState("Local model unavailable");recordError(request,e,"Evidence search failed")}finally{if(current(request))setBusy(false)}}
  async function cite(sourceId:string){const request=requestRef.current;if(!request)return;setBusy(true);try{const result=await api.search(sourceId,undefined,"all",request.controller.signal);if(!current(request))return;setHitsState({applicationId:request.applicationId,value:result.hits});const source=result.hits.find(x=>x.source_id===sourceId)??result.hits[0];if(source)setOpenedState({applicationId:request.applicationId,value:source});setActive(3)}catch(e){recordError(request,e,"Citation lookup failed")}finally{if(current(request))setBusy(false)}}
  async function review(action:string){const request=requestRef.current;if(!selected||!proposal||!request||request.applicationId!==selected.application_id)return;setBusy(true);try{const idempotencyKey=`${selected.application_id}-${proposal.calculation_version}-${action}`;const event=await api.decide(selected.application_id,proposal,action,reviewNote,idempotencyKey,request.controller.signal);if(!current(request)||event.application_id!==request.applicationId)return;const history=await api.audit(selected.application_id,request.controller.signal);if(!current(request)||history.some(item=>item.application_id!==request.applicationId))return;setAuditsState({applicationId:request.applicationId,value:history});setReviewNote("")}catch(e){recordError(request,e,"Review action failed")}finally{if(current(request))setBusy(false)}}
  // Initial discovery runs once; subsequent investigations are driven by explicit application selection.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const controller=new AbortController();Promise.all([api.health(controller.signal),api.applications(controller.signal)]).then(([health,list])=>{if(controller.signal.aborted)return;setMode(health.retrieval_mode);setApps(list);if(list[0])void investigate(list[0].requirements)}).catch(e=>{if(!controller.signal.aborted)setErrorState({applicationId:"bootstrap",value:e instanceof Error?e.message:"Workspace startup failed"})});return()=>{controller.abort();requestRef.current?.controller.abort()}},[]);
  const complete=useMemo(()=>selected?Object.entries(labels).filter(([k])=>selected[k as keyof Requirements]!=null).length:0,[selected]);
  const selectedScenario=apps.find(item=>item.requirements.application_id===applicationId)?.scenario;const completedSteps=new Set<number>();if(validationState?.applicationId===applicationId)completedSteps.add(0);if(projectsState?.applicationId===applicationId)completedSteps.add(1);if(analysisState?.applicationId===applicationId)completedSteps.add(2);if(hitsState?.applicationId===applicationId)completedSteps.add(3);if(svgState?.applicationId===applicationId&&Boolean(svgState.value))completedSteps.add(4);if(auditsState?.applicationId===applicationId&&auditsState.value.length>0)completedSteps.add(5);
  return <main className="shell">
    <header className="topbar"><div className="brand"><span className="mark" aria-hidden="true">N/</span><div><small className="umbrella">Noctra</small><strong>Engineering Application Intelligence</strong><small>Northstar Thermal Systems · Fictional demonstration environment</small></div></div><div className="system-state"><span className={mode==="postgresql_pgvector"?"dot ok":"dot warn"}/><div><strong>{mode==="postgresql_pgvector"?"PGVECTOR ACTIVE":"COMPATIBILITY VECTOR MODE"}</strong><small>Local embedding retrieval · no generative model</small></div></div></header>
    <section className={selected?"hero contextual":"hero"}><div className="hero-copy"><p className="eyebrow">ENGINEERING INVESTIGATION / NTS-WS-01</p><h1>{selected?`${selected.application_id} / ${selectedScenario?scenarioName[selectedScenario]:"Application investigation"}`:"Turn application requirements into a reviewable preliminary concept."}</h1><p className="lede">{selected?"Application-owned requirements, retrieved evidence, deterministic calculations and review state.":"Controlled extraction, traceable retrieval, deterministic engineering checks, and a human decision boundary in one local workspace."}</p></div><div className="hero-metrics"><Metric label="Application" value={selected?.application_id??"—"}/><Metric label="Technical fields" value={`${complete}/${Object.keys(labels).length}`}/><Metric label="Preliminary status" value={analysis?.status.replaceAll("_"," ")??(busy?"Investigating":"Not investigated")}/><Metric label="Review state" value={audits.at(-1)?.after_state.replaceAll("_"," ")??"Not reviewed"}/></div></section>
    <nav className="stepnav" aria-label="Investigation stages">{steps.map((step,i)=>{const done=completedSteps.has(i);return <button key={step} className={`${active===i?"active ":""}${done?"complete":""}`.trim()} aria-current={active===i?"step":undefined} onClick={()=>setActive(i)}><span className="step-number">0{i+1}</span><span className="step-label">{step}</span>{done&&<span className="step-complete" aria-label={`${step} complete`}>✓</span>}</button>})}</nav>
    {error&&<div className="alert error" role="alert"><strong>Investigation exception</strong><span>{error}</span><button onClick={()=>setErrorState(null)}>Dismiss</button></div>}
    {busy&&<div className="progress" aria-label="Working"><span/></div>}
    <div className="workspace">
      <aside className="rail"><p className="rail-title">Application portfolio / 05 cases</p>{apps.map((app)=><button key={app.requirements.application_id} className={`case scenario-${app.scenario}${selected?.application_id===app.requirements.application_id?" active":""}`} aria-pressed={selected?.application_id===app.requirements.application_id} onClick={()=>void investigate(app.requirements)}><span>{app.requirements.application_id}</span><strong>{scenarioName[app.scenario]}</strong><small>{app.requirements.heat_load_kw??"—"} kW · {app.requirements.redundancy?.replaceAll("_"," ")??"input pending"}</small></button>)}<label className="upload"><span>＋</span><strong>Upload controlled PDF</strong><small>NTS-CAF-001 · PDF only · 5 MB max</small><input type="file" accept="application/pdf" onChange={e=>void upload(e.target.files?.[0])}/></label><div className="boundary"><strong>Method boundary / V1</strong><p>Version one reads only the controlled digital form. No scanned or arbitrary documents.</p></div></aside>
      <section className="canvas">
        {active===0&&selected&&<Intake req={selected} validation={validation} onNext={()=>setActive(1)}/>}
        {active===1&&(projectsState&&projectsState.applicationId===applicationId?<Comparables projects={projects} onOpen={x=>applicationId&&setOpenedState({applicationId,value:x})} onNext={()=>setActive(2)}/>:<StagePending busy={busy}/>)}
        {active===2&&analysis&&<AnalysisView analysis={analysis} onCite={id=>void cite(id)} onNext={()=>setActive(3)}/>}
        {active===2&&!analysis&&<StagePending busy={busy}/>}
        {active===3&&<Evidence hits={hits.length?hits:projects} question={question} setQuestion={setQuestion} ask={()=>void ask()} embedState={embedState} onOpen={x=>applicationId&&setOpenedState({applicationId,value:x})}/>}
        {active===4&&<Schematic svg={svg} architecture={analysis&&isDrawable(analysis)?analysis.proposed_architecture:null} loading={busy||!analysis}/>}
        {active===5&&(analysis&&proposal?<Review analysis={analysis} proposal={proposal} note={reviewNote} setNote={setReviewNote} review={a=>void review(a)} audits={audits}/>:<StagePending busy={busy}/>)}
      </section>
    </div>
    {opened&&<div className="drawer" role="dialog" aria-modal="true" aria-label="Evidence source"><button className="scrim" onClick={()=>setOpenedState(null)} aria-label="Close evidence"/><article><button className="close" onClick={()=>setOpenedState(null)}>Close ×</button><p className="eyebrow">{opened.document_type.replaceAll("_"," ")} · {opened.source_id}</p><h2>{opened.title}</h2><div className="source-meta"><span>Rev {opened.revision}</span><span className={`status ${opened.status}`}>{evidenceDesignation(opened)}</span><span>{opened.locator}</span></div><p>{opened.excerpt}</p>{!opened.recommendation_eligible&&<div className="alert error"><strong>{evidenceDesignation(opened)}</strong><span>{opened.disqualification_reasons.join("; ")}</span></div>}<h3>Transparent relevance score</h3>{opened.score_breakdown.map(x=><div className="scoreline" key={x.name}><span>{x.name.replaceAll("_"," ")}</span><progress value={x.raw} max="1"/><b>{(x.raw*100).toFixed(1)}% · {(x.contribution*100).toFixed(1)} pts</b></div>)}<p className="fictional">FICTIONAL CONTROLLED SOURCE</p></article></div>}
    <footer><span>© 2026 Adeel Tagar. All rights reserved.</span><span>Northstar Thermal Systems · Fictional demonstration environment</span><span>Preliminary engineering only · qualified human review required</span></footer>
  </main>
}

function Metric({label,value}:{label:string;value:string}){return <p><span>{label}</span><strong>{value}</strong></p>}
function Intake({req,validation,onNext}:{req:Requirements;validation:Validation|null;onNext:()=>void}){return <><SectionHead index="01" kicker="Controlled intake" title={`${req.application_id} requirements`} copy="Customer-provided values remain visually distinct from calculations, evidence, and system inference."/><div className="status-strip"><span className={validation?.issues.length?"signal warn":"signal ok"}/><strong>{validation?.issues.length?`${validation.issues.length} validation finding(s)`:"Form is complete and internally consistent"}</strong><small>normalized to kW · °C · L/min · kPa · V · Hz · mm</small></div><div className="requirements">{Object.entries(labels).map(([key,label],index)=><div key={key} className={validation?.issues.some(x=>x.field===key)?"requirement flagged":"requirement"}><b className="field-index">{String(index+1).padStart(2,"0")}</b><span>{label}</span><strong>{String(req[key as keyof Requirements]??"Missing")} {req[key as keyof Requirements]!=null?units[key]??"":""}</strong><small>{validation?.issues.find(x=>x.field===key)?.message??"Customer-provided requirement"}</small></div>)}</div><div className="notes"><span>Customer notes / customer-provided requirement</span><p>{req.customer_notes||"No notes supplied."}</p></div><Action onClick={onNext}>Investigate comparable designs →</Action></>}
function Comparables({projects,onOpen,onNext}:{projects:Hit[];onOpen:(x:Hit)=>void;onNext:()=>void}){return <><SectionHead index="02" kicker="Historical investigation" title="Comparable design ledger" copy="Each score exposes six weighted components. Relevance and recommendation eligibility are separate decisions."/><div className="formula"><span>RANKING FORMULA / NTS-RET-1.0</span><b>35% semantic · 15% keyword · 20% numerical · 15% hard constraints · 5% revision · 10% validation</b></div><div className="table-wrap" tabIndex={0} aria-label="Comparable-design ledger, horizontally scrollable"><table><caption>Ranked historical engineering projects</caption><thead><tr><th>Rank / project</th><th>Architecture</th><th>Score</th><th>Constraint deltas</th><th>Eligibility / evidence status</th><th/></tr></thead><tbody>{projects.map((p,i)=><tr key={p.source_id} className={!p.recommendation_eligible?"disqualified":""}><td><small>{String(i+1).padStart(2,"0")}</small><strong>{p.source_id}</strong><span>{p.title}</span></td><td>{p.product_architecture.replaceAll("_"," ")}</td><td><b>{p.score.toFixed(1)}</b><small> / 100 relevance</small></td><td>{p.differences&&<>{String(p.differences.heat_load_kw)} kW Δ<br/>{String(p.differences.flow_lpm)} L/min Δ</>}</td><td><span className={p.recommendation_eligible?"pill eligible":"pill blocked"}>{evidenceDesignation(p)}</span>{!p.recommendation_eligible&&<small className="reason">{p.disqualification_reasons.join("; ")}</small>}</td><td><button className="text-button" onClick={()=>onOpen(p)}>Open ↗</button></td></tr>)}</tbody></table></div><Action onClick={onNext}>Run preliminary engineering analysis →</Action></>}
function AnalysisView({analysis,onCite,onNext}:{analysis:Analysis;onCite:(id:string)=>void;onNext:()=>void}){return <><SectionHead index="03" kicker="Deterministic engineering" title="Preliminary assessment" copy="Controlled Python rules and templates compose this assessment. No language model generates the conclusion."/><div className={`verdict ${analysis.status}`}><span>PRELIMINARY STATUS</span><h3>{analysis.status.replaceAll("_"," ")}</h3><p>{analysis.assessment}</p><small>{analysis.calculation_version}</small></div><div className="calc-grid">{analysis.calculations.map(c=><article key={c.calculation_id} className={c.passed===false?"fail":""}><header><span>DETERMINISTIC CALCULATION</span><b>{c.passed===true?"PASS":c.passed===false?"REVIEW":"OPEN"}</b></header><h3>{c.label}</h3><strong>{String(c.result)} {c.unit}</strong><code>{c.expression}</code><div>{c.source_ids.map(id=><button key={id} onClick={()=>onCite(id)}>{id}</button>)}</div></article>)}</div><h3 className="subhead">Traceable assessment claims</h3><div className="claims">{analysis.claims.map(c=><article key={c.claim_id} className={`claim ${c.category}`}><span>{c.category.replaceAll("_"," ")}</span><p>{c.text}</p><div>{c.source_ids.map(id=><button key={id} onClick={()=>onCite(id)}>[{id}]</button>)}</div></article>)}</div><Action onClick={onNext}>Inspect evidence and citations →</Action></>}
function Evidence({hits,question,setQuestion,ask,embedState,onOpen}:{hits:Hit[];question:string;setQuestion:(x:string)=>void;ask:()=>void;embedState:string;onOpen:(x:Hit)=>void}){return <><SectionHead index="04" kicker="Evidence workspace" title="Bounded evidence inquiry" copy="The question is embedded locally in the browser. Retrieved passages are evidence; they do not generate an engineering conclusion."/><div className="question"><label htmlFor="question">Contextual engineering question</label><div><input id="question" value={question} onChange={e=>setQuestion(e.target.value)}/><button onClick={ask}>Retrieve evidence</button></div><small>{embedState} · bundled ONNX/WASM · remote model access disabled</small></div><div className="evidence-grid">{hits.map(h=><article key={h.source_id} className={`${h.status==="superseded"?"superseded ":""}${!h.recommendation_eligible?"evidence-only":""}`.trim()}><header><span>{h.source_id}</span><span className={`status ${h.status}`}>{evidenceDesignation(h)}</span></header><h3>{h.title}</h3><p>{h.excerpt}</p>{!h.recommendation_eligible&&<small className="reason">{h.disqualification_reasons.join("; ")}</small>}<footer><span>{h.document_type.replaceAll("_"," ")} · Rev {h.revision}</span><b>{h.score.toFixed(1)} relevance</b><button onClick={()=>onOpen(h)}>Open source ↗</button></footer></article>)}</div></>}
function Schematic({svg,architecture,loading}:{svg:string;architecture?:string|null;loading:boolean}){return <><SectionHead index="05" kicker="Parameterized concept" title="Preliminary system schematic" copy="The drawing changes by architecture and redundancy. It is structured for a future DXF exporter, but is not CAD or a manufacturing drawing."/><div className="drawing-meta"><span>Architecture</span><strong>{architecture?.replaceAll("_"," ")??"Not Selected"}</strong><span>Drawing version</span><strong>NTS-SVG-1.1</strong></div>{svg?<div className="schematic" dangerouslySetInnerHTML={{__html:svg}}/>:<div className="empty">{loading?"Investigating the selected application…":"No supported architecture can be drawn until critical requirements are resolved."}</div>}<div className="alert caution"><strong>Drawing boundary</strong><span>Concept topology and customer envelope only. No tolerances, fabrication dimensions, materials, or manufacturing release.</span></div></>}
function Review({analysis,proposal,note,setNote,review,audits}:{analysis:Analysis;proposal:Proposal;note:string;setNote:(x:string)=>void;review:(a:string)=>void;audits:Audit[]}){const allowed=(action:string)=>proposal.allowed_actions.includes(action);return <><SectionHead index="06" kicker="Human decision boundary" title="Concept review gate" copy="A review action records the evidence set, calculation version, state transition, note, and idempotency key in the local fictional audit trail."/><div className="review-grid"><section><h3>Review packet</h3><dl><dt>Application</dt><dd>{analysis.application_id}</dd><dt>Proposed architecture</dt><dd>{analysis.proposed_architecture?.replaceAll("_"," ")??"None"}</dd><dt>Evidence reviewed</dt><dd>{proposal.evidence_source_ids.join(", ")}</dd><dt>Calculation version</dt><dd>{proposal.calculation_version}</dd><dt>Missing warnings</dt><dd>{analysis.missing_requirements.join(", ")||"None"}</dd></dl>{!proposal.approval_permitted&&<div className="alert error"><strong>Approval prohibited</strong><span>{proposal.prohibited_reasons.join("; ")}</span></div>}<label className="review-note">Reviewer note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Record the engineering basis for this local fictional decision."/></label><div className="review-actions"><button disabled={!proposal.approval_permitted||!allowed("approve_for_concept_review")||note.length<3} onClick={()=>review("approve_for_concept_review")}>Approve for concept review</button><button disabled={!allowed("return_for_additional_information")||note.length<3} onClick={()=>review("return_for_additional_information")}>Return for additional information</button><button disabled={!allowed("reject_preliminary_configuration")||note.length<3} onClick={()=>review("reject_preliminary_configuration")}>Reject preliminary configuration</button></div></section><section><h3>Audit history</h3>{audits.length===0?<div className="empty">No human review action recorded for this application.</div>:<div className="timeline">{audits.map(a=><article key={a.idempotency_key}><span>{new Date(a.timestamp).toLocaleString()}</span><strong>{a.reviewer_action.replaceAll("_"," ")}</strong><p>{a.reviewer_note}</p><small>{a.before_state} → {a.after_state}<br/>{a.idempotency_key}</small></article>)}</div>}</section></div></>}
function SectionHead({index,kicker,title,copy}:{index:string;kicker:string;title:string;copy:string}){return <header className="section-head"><span>{index}</span><div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div><p>{copy}</p></header>}
function StagePending({busy}:{busy:boolean}){return <div className="empty">{busy?"Investigating the selected application…":"This stage has not been investigated for the selected application."}</div>}
function Action({children,onClick}:{children:React.ReactNode;onClick:()=>void}){return <div className="next-action"><button onClick={onClick}>{children}</button></div>}
